#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook "apt"
cookbook "git"
cookbook "vim"
cookbook "python"
cookbook "nodejs"
cookbook "build-essential"
cookbook "java"
cookbook "vim_config",
  :git => "https://github.com/nathanph/cookbook-vim_config"
cookbook 'golang'